[package]
name = "beancount_parser_2"
version = "1.0.0-beta.4"
license = "Unlicense"
authors = ["Jonathan Cornaz"]
edition = "2021"
rust-version = "1.70.0"
description = "[DISCONTINUED]: See `beancount-parser` instead"
repository = "https://github.com/jcornaz/beancount_parser_2"
categories = ["parser-implementations"]
keywords = ["parsing", "beancount", "accounting"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
# Public

# Private
nom = { version = "7.1.3", default-features = false, features = ["std"] }
nom_locate = { version = "4.1.0", default-features = false }

[dev-dependencies]
criterion = "0.5.1"
rstest = { version = "0.17.0", default-features = false }
rust_decimal = { version = "1.30.0", default-features = false }

[[bench]]
name = "benchmark"
harness = false
